//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectConsole.DataSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.SoapClient.com/xml/SQLDataSoap.wsdl", ConfigurationName="DataSoap.SQLDataSoapPortType")]
    public interface SQLDataSoapPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.SoapClient.com/xml/SQLDataSoap.xsd) of message ProcessSRLRequest does not match the default value (http://www.SoapClient.com/xml/SQLDataSoap.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://soapclient.com/SQLDataSRL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TestProjectConsole.DataSoap.ProcessSRLResponse ProcessSRL(TestProjectConsole.DataSoap.ProcessSRLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soapclient.com/SQLDataSRL", ReplyAction="*")]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> ProcessSRLAsync(TestProjectConsole.DataSoap.ProcessSRLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.SoapClient.com/xml/SQLDataSoap.xsd) of message ProcessSRL2Request does not match the default value (http://www.SoapClient.com/xml/SQLDataSoap.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://soapclient.com/SQLDataSRL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TestProjectConsole.DataSoap.ProcessSRLResponse ProcessSRL2(TestProjectConsole.DataSoap.ProcessSRL2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soapclient.com/SQLDataSRL", ReplyAction="*")]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> ProcessSRL2Async(TestProjectConsole.DataSoap.ProcessSRL2Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.SoapClient.com/xml/SQLDataSoap.xsd) of message ProcessSQLRequest does not match the default value (http://www.SoapClient.com/xml/SQLDataSoap.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.SoapClient.com/SQLDataSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TestProjectConsole.DataSoap.ProcessSQLResponse ProcessSQL(TestProjectConsole.DataSoap.ProcessSQLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.SoapClient.com/SQLDataSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSQLResponse> ProcessSQLAsync(TestProjectConsole.DataSoap.ProcessSQLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSRL", WrapperNamespace="http://www.SoapClient.com/xml/SQLDataSoap.xsd", IsWrapped=true)]
    public partial class ProcessSRLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SRLFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string key;
        
        public ProcessSRLRequest() {
        }
        
        public ProcessSRLRequest(string SRLFile, string RequestName, string key) {
            this.SRLFile = SRLFile;
            this.RequestName = RequestName;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSRLResponse", WrapperNamespace="http://www.SoapClient.com/xml/SQLDataSoap.xsd", IsWrapped=true)]
    public partial class ProcessSRLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ProcessSRLResponse() {
        }
        
        public ProcessSRLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSRL2", WrapperNamespace="http://www.SoapClient.com/xml/SQLDataSoap.xsd", IsWrapped=true)]
    public partial class ProcessSRL2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SRLFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string key1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string key2;
        
        public ProcessSRL2Request() {
        }
        
        public ProcessSRL2Request(string SRLFile, string RequestName, string key1, string key2) {
            this.SRLFile = SRLFile;
            this.RequestName = RequestName;
            this.key1 = key1;
            this.key2 = key2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSQL", WrapperNamespace="http://www.SoapClient.com/xml/SQLDataSoap.xsd", IsWrapped=true)]
    public partial class ProcessSQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DataSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SQLStatement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Password;
        
        public ProcessSQLRequest() {
        }
        
        public ProcessSQLRequest(string DataSource, string SQLStatement, string UserName, string Password) {
            this.DataSource = DataSource;
            this.SQLStatement = SQLStatement;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSQLResponse", WrapperNamespace="http://www.SoapClient.com/xml/SQLDataSoap.xsd", IsWrapped=true)]
    public partial class ProcessSQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ProcessSQLResponse() {
        }
        
        public ProcessSQLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SQLDataSoapPortTypeChannel : TestProjectConsole.DataSoap.SQLDataSoapPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQLDataSoapPortTypeClient : System.ServiceModel.ClientBase<TestProjectConsole.DataSoap.SQLDataSoapPortType>, TestProjectConsole.DataSoap.SQLDataSoapPortType {
        
        public SQLDataSoapPortTypeClient() {
        }
        
        public SQLDataSoapPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQLDataSoapPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLDataSoapPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLDataSoapPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProjectConsole.DataSoap.ProcessSRLResponse TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSRL(TestProjectConsole.DataSoap.ProcessSRLRequest request) {
            return base.Channel.ProcessSRL(request);
        }
        
        public string ProcessSRL(string SRLFile, string RequestName, string key) {
            TestProjectConsole.DataSoap.ProcessSRLRequest inValue = new TestProjectConsole.DataSoap.ProcessSRLRequest();
            inValue.SRLFile = SRLFile;
            inValue.RequestName = RequestName;
            inValue.key = key;
            TestProjectConsole.DataSoap.ProcessSRLResponse retVal = ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSRL(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSRLAsync(TestProjectConsole.DataSoap.ProcessSRLRequest request) {
            return base.Channel.ProcessSRLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> ProcessSRLAsync(string SRLFile, string RequestName, string key) {
            TestProjectConsole.DataSoap.ProcessSRLRequest inValue = new TestProjectConsole.DataSoap.ProcessSRLRequest();
            inValue.SRLFile = SRLFile;
            inValue.RequestName = RequestName;
            inValue.key = key;
            return ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSRLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProjectConsole.DataSoap.ProcessSRLResponse TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSRL2(TestProjectConsole.DataSoap.ProcessSRL2Request request) {
            return base.Channel.ProcessSRL2(request);
        }
        
        public string ProcessSRL2(string SRLFile, string RequestName, string key1, string key2) {
            TestProjectConsole.DataSoap.ProcessSRL2Request inValue = new TestProjectConsole.DataSoap.ProcessSRL2Request();
            inValue.SRLFile = SRLFile;
            inValue.RequestName = RequestName;
            inValue.key1 = key1;
            inValue.key2 = key2;
            TestProjectConsole.DataSoap.ProcessSRLResponse retVal = ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSRL2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSRL2Async(TestProjectConsole.DataSoap.ProcessSRL2Request request) {
            return base.Channel.ProcessSRL2Async(request);
        }
        
        public System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSRLResponse> ProcessSRL2Async(string SRLFile, string RequestName, string key1, string key2) {
            TestProjectConsole.DataSoap.ProcessSRL2Request inValue = new TestProjectConsole.DataSoap.ProcessSRL2Request();
            inValue.SRLFile = SRLFile;
            inValue.RequestName = RequestName;
            inValue.key1 = key1;
            inValue.key2 = key2;
            return ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSRL2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestProjectConsole.DataSoap.ProcessSQLResponse TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSQL(TestProjectConsole.DataSoap.ProcessSQLRequest request) {
            return base.Channel.ProcessSQL(request);
        }
        
        public string ProcessSQL(string DataSource, string SQLStatement, string UserName, string Password) {
            TestProjectConsole.DataSoap.ProcessSQLRequest inValue = new TestProjectConsole.DataSoap.ProcessSQLRequest();
            inValue.DataSource = DataSource;
            inValue.SQLStatement = SQLStatement;
            inValue.UserName = UserName;
            inValue.Password = Password;
            TestProjectConsole.DataSoap.ProcessSQLResponse retVal = ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSQL(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSQLResponse> TestProjectConsole.DataSoap.SQLDataSoapPortType.ProcessSQLAsync(TestProjectConsole.DataSoap.ProcessSQLRequest request) {
            return base.Channel.ProcessSQLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestProjectConsole.DataSoap.ProcessSQLResponse> ProcessSQLAsync(string DataSource, string SQLStatement, string UserName, string Password) {
            TestProjectConsole.DataSoap.ProcessSQLRequest inValue = new TestProjectConsole.DataSoap.ProcessSQLRequest();
            inValue.DataSource = DataSource;
            inValue.SQLStatement = SQLStatement;
            inValue.UserName = UserName;
            inValue.Password = Password;
            return ((TestProjectConsole.DataSoap.SQLDataSoapPortType)(this)).ProcessSQLAsync(inValue);
        }
    }
}
